return function(require)
	local C = require("ui.components")
	local State = require("core.state")
	local Config = require("core.config")
	local Notify = require("ui.notify")
	local Visuals = require("systems.utility.visuals")

	return function(parent)
		local scroll = C.scroll(parent)
		local sec = C.section(scroll, "LIGHTING")
		C.toggle(sec, "Fullbright", function()
			return State.getToggle("fullbright")
		end, function(v)
			Visuals.fullbright(v)
			Config.save()
			Notify.info("Visuals", v and "Fullbright ON" or "OFF")
		end)
		local row = C.row(sec)
		C.button(row, "Day", function()
			Visuals.day()
		end, { w = 100, h = 34 })
		C.button(row, "Night", function()
			Visuals.night()
		end, { w = 100, h = 34 })
	end
end
